### ISSUE TITLE
Things todo

### ISSUE THREAD

**Issue by tamoore** [tamoore/Example-Style-Guide#1]
- [ ] Eject create-react-app
- [ ] Create a script for outputting only included packages
- [ ] Adding a raw! loader to the example app
- [ ] Generate props from the raw source code
